/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.base;

import gui.terminal.AdminTerminal;
import methods.Autobus;
import methods.Base;
import methods.Direccion;
import methods.Empleado;
import methods.Estado;
import methods.Terminal;
import utils.UtilsTable;

/**
 *
 * @author David
 */
public class AdminBase extends javax.swing.JFrame {
    Object listaBases[][];
    Object term[];
    Object dir[];
    Object est[];
    Object emp[];
    Object listaAutobuses[][];
    
    AgregarBase agB;
    ActualizarBase acB;
    Base base;
    Terminal terminal;
    Direccion direccion;
    Estado estado;
    Autobus autobus;
    Empleado empleado;
    /**
     * Creates new form AdminBase
     */
    public AdminBase() {
        initComponents();
        base = new Base();
        autobus = new Autobus();
        terminal = new Terminal();
        direccion = new Direccion();
        estado = new Estado();
        empleado = new Empleado();
        
        mostrarBases();
    }
    
    public void mostrarBases() {
        listaBases = base.selectBases();
        listaAutobuses = autobus.selectAutobuses();
        int[] num = new int[listaBases.length];
        for( int c=0; c<listaAutobuses.length; c++ )
            num[Integer.parseInt(listaAutobuses[c][4].toString())-1]++;
        Object[][] listaT = new Object[listaBases.length][6]; 
        for( int i = 0; i<listaBases.length; i++ )
        {
            listaT[i][0] = listaBases[i][0];
            term = terminal.selectTerminal(Integer.parseInt(listaBases[i][1].toString()));
            emp = empleado.selectEmpleado(Integer.parseInt(term[3].toString()));
            dir = direccion.selectDireccion(Integer.parseInt(term[2].toString()));
            est = estado.selectEstado(Integer.parseInt(dir[8].toString()));
            listaT[i][1] = est[1].toString();
            listaT[i][2] = term[1].toString();
            listaT[i][3] = emp[1].toString();
            listaT[i][4] = dir[1].toString();
            listaT[i][5] = num[i];
        }
        String[] T_BASES = {"ID","Estado", "Terminal", "Gerente", "Ciudad","No. de Autobuses"};
        int[][] cellAlignment = {{0,javax.swing.SwingConstants.LEFT}};
        int[][] cellSize = {{0,30},
                            {1,80},
                            {2,100},
                            {3,100},
                            {4,100},
                            {5,110}};
        // pone los datos en la tabla
        UtilsTable.llenaTabla(TablaBases,listaT, 
                T_BASES, cellAlignment, cellSize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaBases = new javax.swing.JTable();
        BotonAgregarBase = new javax.swing.JButton();
        BotonEditarBase = new javax.swing.JButton();
        BotonEliminarBase = new javax.swing.JButton();
        BotonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));

        jLabel9.setFont(new java.awt.Font("Broadway", 0, 72)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADE");

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Autobuses del Este");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMINISTRAR BASES");

        TablaBases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaBases.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(TablaBases);

        BotonAgregarBase.setText("AGREGAR BASE");
        BotonAgregarBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarBaseActionPerformed(evt);
            }
        });

        BotonEditarBase.setText("EDITAR BASE");
        BotonEditarBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarBaseActionPerformed(evt);
            }
        });

        BotonEliminarBase.setText("ELIMINAR BASE");
        BotonEliminarBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarBaseActionPerformed(evt);
            }
        });

        BotonRegresar.setText("REGRESAR");
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotonEditarBase, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonAgregarBase, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonEliminarBase, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonAgregarBase, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonEditarBase, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonEliminarBase, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarBaseActionPerformed
        AgregarBase agB = new AgregarBase();
        agB.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonAgregarBaseActionPerformed

    private void BotonEditarBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarBaseActionPerformed
        if (TablaBases.getSelectedRow() < 0)
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una fila.","Información",1);
        else
        {
            Object[] editBase = base.selectBase(Integer.parseInt(TablaBases.getValueAt(TablaBases.getSelectedRow(), 0).toString()));

            ActualizarBase actB = new ActualizarBase(Integer.parseInt(editBase[0].toString()));
            actB.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_BotonEditarBaseActionPerformed

    private void BotonEliminarBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarBaseActionPerformed
        int r = base.deleteBase( Integer.parseInt(listaBases[TablaBases.getSelectedRow() ][0].toString()) ); //Elimina el registro
        switch (r) {
            case 0:
                javax.swing.JOptionPane.showMessageDialog(this, "Base eliminada correctamente.","Aviso",1);
                break;
            case 1:
                javax.swing.JOptionPane.showMessageDialog(this, "No se puede borrar el registro.","Aviso",1);
                break;
            default:
                javax.swing.JOptionPane.showMessageDialog(this, "Ocurrio un error al intentar borrar la base.","Aviso",1);
                break;
        }
        listaBases = base.selectBases();
        mostrarBases();
    }//GEN-LAST:event_BotonEliminarBaseActionPerformed

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        AdminTerminal t = new AdminTerminal();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarBase;
    private javax.swing.JButton BotonEditarBase;
    private javax.swing.JButton BotonEliminarBase;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JTable TablaBases;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
